image: tiokksar/karma
script:
  - npm install
  - karma start --single-run
deploy:
  heroku:
    app: paired-dev
    force: true
notify:
  email:
    recipients:
      - rpallas@gmail.com
#cache:
#  - .npm
