image: tiokksar/karma
script:
  # workaround for cache, see https://github.com/drone/drone/issues/147
  - mkdir -p /tmp/npm
  - npm config set cache /tmp/npm
  # actual script:
  - npm install grunt-cli -g
#  - npm install
  - npm test
deploy:
  heroku:
    app: paired-dev
    force: true
notify:
  email:
    recipients:
      - rpallas@gmail.com
cache:
  - /tmp/npm
