image: tiokksar/karma
script:
  - npm install -g bower
  - bower install --allow-root
  - npm install
  - karma start --single-run
deploy:
  heroku:
    app: nameless-cove-8544
notify:
  email:
    recipients:
      - rpallas@gmail.com